{
 "title": "Temperature",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Room temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "deconz_temperature", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Floor temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "deconz_floortemperature", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Heat setpoint temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "deconz_heatsetpoint", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Heating",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "deconz_heating", "legendFormat": "{{name}}" }
   ]
  }
 ]
}